


version: "3.8"                  ## Docker Compose - Reality

services:
  nginx-wp5:
    image: nginx:latest                  ## Power
    container_name: wp5-nginx
    ports:
      - "9097:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - wp5_data:/var/www/html
    depends_on:
      - wp5
    restart: always



  wp5:
    image: wordpress:php8.2-fpm                  ## Mind
    container_name: wp5-wordpress
    environment:
      WORDPRESS_DB_HOST: db5:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wp123
      WORDPRESS_DB_NAME: db5
      WORDPRESS_REDIS_HOST: redis5
    volumes:
      - wp5_data:/var/www/html
    depends_on:
      - db5
      - redis5
    restart: always



  db5:
    image: mariadb:10.6                  ##  Soul 
    container_name: wp5-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db5
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wp123
    volumes:
      - db5_data:/var/lib/mysql
    restart: always




  redis5:                  ## Time
    image: redis:alpine
    container_name: wp5-redis
    restart: always

volumes:
  wp5_data:
  db5_data:

